# Generated by Django 5.2.17 on 2026-09-26 01:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("identity", "0002_alter_delegation_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseIntelligence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cases.case"
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intelligence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("classification", models.PositiveSmallIntegerField(default=0)),
                ("subject", models.CharField(max_length=240)),
                ("summary", models.TextField(max_length=4000)),
                ("provenance", models.CharField(max_length=120)),
                ("occurred_on", models.DateField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_intelligence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cases",
                    models.ManyToManyField(
                        related_name="intelligence",
                        through="intelligence.CaseIntelligence",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_intelligence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="identity.unit"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Dissemination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(max_length=80)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("expected_action", models.CharField(max_length=500)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="identity.unit"
                    ),
                ),
                (
                    "intelligence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disseminations",
                        to="intelligence.intelligence",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="caseintelligence",
            name="intelligence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="intelligence.intelligence",
            ),
        ),
        migrations.CreateModel(
            name="ProtectedSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.TextField(max_length=1000)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intelligence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protected_source",
                        to="intelligence.intelligence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisseminationReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("acknowledged", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=1000)),
                ("idempotency_key", models.UUIDField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dissemination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="intelligence.dissemination",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["received_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dissemination", "idempotency_key"),
                        name="unique_return_retry",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="intelligence",
            index=models.Index(
                fields=["unit", "created_at"], name="intelligenc_unit_id_ddbf8a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="intelligence",
            constraint=models.CheckConstraint(
                condition=models.Q(("classification__in", [0, 1])),
                name="intelligence_classification_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="dissemination",
            constraint=models.UniqueConstraint(
                fields=("intelligence", "idempotency_key"),
                name="unique_dissemination_retry",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseintelligence",
            constraint=models.UniqueConstraint(
                fields=("intelligence", "case"), name="unique_case_intelligence"
            ),
        ),
    ]
