# Generated by Django 5.2.17 on 2026-09-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegation",
            name="action",
            field=models.CharField(
                choices=[
                    ("case.create", "Créer un dossier"),
                    ("case.assign", "Affecter un dossier"),
                    ("audit.read", "Lire l'audit"),
                    ("intelligence.distribute", "Diffuser un renseignement"),
                    ("source.read", "Lire une source protégée"),
                    ("source.write", "Enregistrer une source protégée"),
                ],
                max_length=32,
            ),
        ),
    ]
