# Generated by Django 5.2.17 on 2026-09-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_alter_delegation_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegation",
            name="action",
            field=models.CharField(
                choices=[
                    ("case.create", "Créer un dossier"),
                    ("case.assign", "Affecter un dossier"),
                    ("audit.read", "Lire l'audit"),
                    ("intelligence.distribute", "Diffuser un renseignement"),
                    ("source.read", "Lire une source protégée"),
                    ("source.write", "Enregistrer une source protégée"),
                    ("request.validate", "Valider une demande"),
                    ("request.sign", "Constater la signature"),
                    ("request.issue", "Constater l'émission"),
                ],
                max_length=32,
            ),
        ),
    ]
