# Generated by Django 5.2.17 on 2026-09-26 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("documents", "0001_initial"),
        ("inspections", "0001_initial"),
        ("requests_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("classification", "Classement sans suite"),
                            ("mission", "Mission complémentaire"),
                            ("complement", "Demande de complément"),
                            ("gelec", "Relais GELEC"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposée"),
                            ("returned", "Retournée"),
                            ("validated", "Validée"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("return_comment", models.CharField(blank=True, max_length=500)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prototype_only", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="cases.case",
                    ),
                ),
                (
                    "observation_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inspections.observationassessment",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="decisions.decision",
                    ),
                ),
                (
                    "request_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="requests_app.itemassessment",
                    ),
                ),
                (
                    "validator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validated_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DecisionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="decisions.decision",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="GelecTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prepared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("prepared", "Préparé"),
                            ("transmitted", "Transmis"),
                            ("confirmed", "Réception confirmée"),
                        ],
                        default="prepared",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("transmission_reference", models.CharField(blank=True, max_length=120)),
                ("transmission_key", models.UUIDField(blank=True, null=True)),
                ("transmitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transmission_recorded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("confirmation_key", models.UUIDField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_recorded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("prototype_only", models.BooleanField(default=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_gelec_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gelec_transfer",
                        to="decisions.decision",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_gelec_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt_proof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gelec_receipt_proofs",
                        to="documents.document",
                    ),
                ),
                (
                    "transmission_proof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gelec_transmission_proofs",
                        to="documents.document",
                    ),
                ),
                (
                    "transmitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmitted_gelec_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("observation_assessment__isnull", True),
                        ("request_assessment__isnull", False),
                    ),
                    models.Q(
                        ("observation_assessment__isnull", False),
                        ("request_assessment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="decision_one_assessment",
            ),
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "proposed")),
                fields=("case",),
                name="one_proposed_decision_per_case",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisionevent",
            constraint=models.UniqueConstraint(
                fields=("decision", "version"), name="unique_decision_event_version"
            ),
        ),
    ]
