# Generated by Django 5.2.17 on 2026-09-26 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("broker", "Commissionnaire en douane"),
                            ("organization", "Entreprise ou ONG"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_name", models.CharField(max_length=240)),
                ("represented_name", models.CharField(blank=True, max_length=240)),
                ("subject", models.CharField(max_length=240)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("generated", "Format Procezo"),
                            ("imported", "Document de l'agent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_on", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis"),
                            ("validated", "Validé"),
                            ("signed", "Signature constatée"),
                            ("issued", "Émis"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communication_requests",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ActVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_version", models.PositiveIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("generated", "Format Procezo"),
                            ("imported", "Document de l'agent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("storage_name", models.UUIDField(blank=True, null=True, unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("prepared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.document",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acts",
                        to="requests_app.communicationrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=500)),
                ("assessment_version", models.PositiveIntegerField(default=0)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="requests_app.communicationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="ItemAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "receipt",
                    models.CharField(
                        choices=[("not_received", "Non reçu"), ("received", "Reçu")],
                        max_length=20,
                    ),
                ),
                (
                    "completeness",
                    models.CharField(
                        choices=[
                            ("unknown", "Non évalué"),
                            ("complete", "Complet"),
                            ("insufficient", "Insuffisant"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "substance",
                    models.CharField(
                        choices=[
                            ("pending", "Non apprécié"),
                            ("satisfactory", "Satisfaisant"),
                            ("unsatisfactory", "Non satisfaisant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="requests_app.requesteditem",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
            },
        ),
        migrations.CreateModel(
            name="RequestEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField()),
                ("factual_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "act",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="requests_app.actversion",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.document",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="requests_app.communicationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RequestResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("received_on", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "annexes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="response_annexes",
                        to="documents.document",
                    ),
                ),
                (
                    "complement_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="requests_app.requestresponse",
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="response_letters",
                        to="documents.document",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="requests_app.communicationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["received_on", "recorded_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseItemLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="added_response_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="response_links",
                        to="requests_app.requesteditem",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_links",
                        to="requests_app.requestresponse",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voided_response_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestIssuance",
            fields=[
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="issuance",
                        serialize=False,
                        to="requests_app.communicationrequest",
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("prototype_only", models.BooleanField(default=True)),
                (
                    "act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="requests_app.actversion",
                    ),
                ),
                (
                    "dispatch_proof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_proofs",
                        to="documents.document",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signature_proof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signature_proofs",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="communicationrequest",
            index=models.Index(
                fields=["case", "state", "created_at"],
                name="requests_ap_case_id_a7e526_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="actversion",
            constraint=models.UniqueConstraint(
                fields=("request", "request_version"), name="unique_request_act_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="requesteditem",
            constraint=models.UniqueConstraint(
                fields=("request", "number"), name="unique_requested_item_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemassessment",
            constraint=models.UniqueConstraint(
                fields=("item", "version"), name="unique_item_assessment_version"
            ),
        ),
    ]
