# Generated by Django 5.2.17 on 2026-09-26 01:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("intelligence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_name", models.CharField(max_length=240)),
                ("content_type", models.CharField(max_length=40)),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("quarantine", "En quarantaine"),
                            ("accepted", "Accepté"),
                            ("rejected", "Rejeté"),
                            ("missing", "Fichier manquant"),
                        ],
                        default="quarantine",
                        max_length=20,
                    ),
                ),
                (
                    "storage_name",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("slot", models.PositiveSmallIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="cases.case",
                    ),
                ),
                (
                    "intelligence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="intelligence.intelligence",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FileOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("result", models.CharField(max_length=24)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("case__isnull", False), ("intelligence__isnull", True)),
                    models.Q(("case__isnull", True), ("intelligence__isnull", False)),
                    _connector="OR",
                ),
                name="document_one_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot__gte", 1), ("slot__lte", 20)),
                name="document_slot_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("case__isnull", False)),
                fields=("case", "slot"),
                name="unique_case_document_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("intelligence__isnull", False)),
                fields=("intelligence", "slot"),
                name="unique_intelligence_document_slot",
            ),
        ),
    ]
