# Generated by Django 5.2.17 on 2026-09-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="classification",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
