# Generated by Django 5.2.17 on 2026-09-26 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("resource_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_events",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="InspectionMission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("context", models.CharField(max_length=500)),
                ("findings", models.TextField(max_length=4000)),
                ("occurred_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions",
                        to="cases.case",
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inspection_missions",
                        to="documents.document",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="inspection_missions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ObservationSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("mission", "Mission"),
                            ("intelligence", "Renseignement"),
                            ("system", "Système"),
                            ("field", "Constat terrain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_address", models.CharField(max_length=500)),
                ("concerned_party", models.CharField(max_length=240)),
                ("facts", models.TextField(max_length=4000)),
                ("version", models.PositiveIntegerField(default=1)),
                ("prototype_only", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observation_sheets",
                        to="cases.case",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sheets",
                        to="inspections.inspectionmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("facts", models.TextField(max_length=2000)),
                ("assessment_version", models.PositiveIntegerField(default=0)),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True, related_name="observations", to="documents.document"
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="inspections.observationsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Defense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("received_on", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annexes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="defense_annexes",
                        to="documents.document",
                    ),
                ),
                (
                    "complement_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inspections.defense",
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defense_letters",
                        to="documents.document",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observations",
                    models.ManyToManyField(
                        related_name="defenses", to="inspections.observation"
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defenses",
                        to="inspections.observationsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["received_on", "recorded_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="SheetProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sheet_version", models.PositiveIntegerField()),
                (
                    "storage_name",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("prepared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="inspections.observationsheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservationAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "conclusion",
                    models.CharField(
                        choices=[
                            ("pending", "À apprécier"),
                            ("satisfactory", "Satisfaisante"),
                            ("unsatisfactory", "Insuffisante"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "defense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inspections.defense",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="inspections.observation",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation", "version"),
                        name="unique_observation_assessment_version",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.UniqueConstraint(
                fields=("sheet", "number"), name="unique_observation_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="sheetproject",
            constraint=models.UniqueConstraint(
                fields=("sheet", "sheet_version"), name="unique_sheet_project_version"
            ),
        ),
    ]
